geosignal_web:
    resource: "@GeosignalWebBundle/Controller/"
    type:     annotation
    prefix:   /
    schemes:  [%httpProtocol%]
    
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin    
    schemes:  [%httpProtocol%]       
